language: node_js
node_js:
  - "11.3.0"
addons:
    code_climate:
        repo_token: ecf35237439f9f7723bad29f533955f0061f3cd44e14fb2d655a57c72a6107fe
script: npm test
before_script:
  - npm install test-reporter -g
  - npm install nyc -g
  - npm install
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
