language: node_js
node_js:
  - "11.3.0"
addons:
    code_climate:
        repo_token: ecf35237439f9f7723bad29f533955f0061f3cd44e14fb2d655a57c72a6107fe
script: istanbul cover node_modules/mocha/bin/_mocha -- -R spec
before_script:
  - npm install codeclimate-test-reporter istanbul -g
  - npm install
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
